### ISSUE TITLE
erro na confirmação da NFe

### ISSUE THREAD

**Issue by Mackilem** [Trust-Code/l10n-brazil#42]
Traceback (most recent call last):
  File "/home/trustcode/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/trustcode/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/home/trustcode/odoo/odoo/openerp/http.py", line 590, in dispatch
    return self._handle_exception(e)
  File "/home/trustcode/odoo/odoo/openerp/http.py", line 544, in _handle_exception
    'data': serialize_exception(exception)
  File "/home/trustcode/odoo/odoo/openerp/http.py", line 596, in serialize_exception
    "message": ustr(e),
  File "/home/trustcode/odoo/odoo/openerp/loglevels.py", line 77, in ustr
    return exception_to_unicode(value)
  File "/home/trustcode/odoo/odoo/openerp/loglevels.py", line 100, in exception_to_unicode
    return "\n".join((ustr(a) for a in e.args))
  File "/home/trustcode/odoo/odoo/openerp/loglevels.py", line 100, in <genexpr>
    return "\n".join((ustr(a) for a in e.args))
  File "/home/trustcode/odoo/odoo/openerp/loglevels.py", line 86, in ustr
    raise UnicodeError('unable to convert %r' % (value,))
  File "xmlerror.pxi", line 286, in lxml.etree._ListErrorLog.__repr__ (src/lxml/lxml.etree.c:33201)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xff' in position 173: ordinal not in range(128)

**Comment by danimaribeiro** [comment]
Deve ter mais log ai, amanhã tu olha o log e vê se tem mais coisas antes disto.

**Comment by danimaribeiro** [comment]
Finalizado.
