### ISSUE TITLE
Erro ao faturar contrato

### ISSUE THREAD

**Issue by paulorsbrito** [Trust-Code/l10n-brazil#65]
Olá!

Estou estudando o módulo de contratos e NFS-e para um cliente e não consigo gerar uma fatura. Acabo sempre com o stacktrace abaixo. Estou usando os branches da versão 8.

Desde já agradeço pela atenção.

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/hr_timesheet_invoice/wizard/hr_timesheet_final_invoice_create.py", line 51, in do_create
    invs = self.pool.get('account.analytic.line').invoice_cost_create(cr, uid, ids, data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/l10n-brazil/l10n_br_hr_timesheet_invoice/hr_timesheet_invoice.py", line 54, in invoice_cost_create
    onchange = inv_obj.onchange_partner_id(cr, uid, [invoice.id], 'out_invoice', invoice.partner_id.id, invoice.date_invoice, payment_term, bank, invoice.company_id.id, fiscal_category_id)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/l10n-brazil/l10n_br_account_withholding/account_invoice.py", line 184, in onchange_partner_id
    partner_bank_id, company_id, fiscal_category_id)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 398, in old_api
    recs = self.browse(cr, uid, ids, context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 5278, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "/opt/odoo/odoo-server/openerp/api.py", line 774, in __new__
    self.cr, self.uid, self.context = self.args = (cr, uid, frozendict(context))
TypeError: 'int' object is not iterable
```

**Comment by danimaribeiro** [comment]
Infelizmente é erro de programação.
Não estamos mais trabalhando na versão 8.0, porém se você enviar a correção eu aceito, mas dificilmente vamos corrigir este.

**Comment by paulorsbrito** [comment]
Obrigado pela resposta rápida. Vocês ainda dão suporte na versão 9?

**Comment by danimaribeiro** [comment]
Estamos trabalhando com a 10.
Se você já estiver usando nós podemos dar suporte, porém não fizemos mais implantação.

**Comment by paulorsbrito** [comment]
Ok, obrigado.

Abraço.
